name: File style
on:
  push: {}
  pull_request: {}

jobs:
  check-encoding:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Check correct encoding etc.
      run: ./contrib/check-encoding.sh
